### ISSUE TITLE
Git practice

### ISSUE THREAD

**Issue by TheStress** [StudioAspen/AAAGame2023-2024#10]
Why are we doing this?
Since you cannot resolve merge conflicts between Unity Scenes everyone will be working from their own scene. This task is about practicing git by creating your own scene using the git workflow.

- Create a FEATURE branch from DEVELOP branch
- Create a scene called "YourNameTestScene", where "YourName" is your name, in the "/Scenes/TestScenes" folder in Unity
- Commit these changes with a message
- Start a pull request that merges your FEATURE branch into the DEVELOP branch

**Comment by lausan3** [comment]
Some of us already did this, do we still need to do it?

**Comment by TheStress** [comment]
Yeah if you did it already you're good. I just converted the task into an issue, I think may have given you a double ping? If so I am sorry about that.
