### ISSUE TITLE
downward stab

### ISSUE THREAD

**Issue by TheStress** [StudioAspen/AAAGame2023-2024#68]
- see https://github.com/StudioAspen/AAAGame2023-2024/wiki/Player-Movement-and-Combat for requirements
- see https://github.com/StudioAspen/AAAGame2023-2024/wiki/Player-Movement-Software-Design-Interactions for the overarching design of the other moves
- Basically, all moves should have some of the same functions as described by the https://github.com/StudioAspen/AAAGame2023-2024/wiki/SwordStab

Note:
- [ ] once the ground eye ball is done integrate the downward stab functionality #72

**Comment by habinpark** [comment]
what should be the way to do the downward stab?
Is it physics based so add a force? or is it move the character in the downwards direction

**Comment by TheStress** [comment]
Yes you should use the `RidgidBody` to move the player. It's up to you how you want to implement it if you wanna use `MovePosition()` or `AddForce()` or anything else. Just make sure it feels right to use
